Use class vars to configure OCPP version of ChargePoint
This commit also fixes issue #31. Due to circular imports importing
certain functions and classes could lead to

	ImportError: cannot import name 'Call'

`ocpp.messages` required `ocpp.v16`, while `ocpp.v16` also imported
`ocpp.messages`.

It has been fixed by making `ocpp.messages` not depedent on `ocpp.v16`.