Update README.rst
The example code has been updated to use the correct enum name RegistrationStatusEnumType instead of RegistrationStatusType.

Before:
```
Traceback (most recent call last):
  File "/Users/erik/Dev/ocpp-proxy/ocpp_server.py", line 9, in <module>
    from ocpp.v201.enums import RegistrationStatusType
ImportError: cannot import name 'RegistrationStatusType' from 'ocpp.v201.enums' (/Users/erik/.asdf/installs/python/3.11.8/lib/python3.11/site-packages/ocpp/v201/enums.py)
```

After:
```
INFO:websockets.server:server listening on 0.0.0.0:9000
INFO:root:WebSocket Server Started
```